language: python
python:
  - "2.7"
install:
  - wget http://repo.continuum.io/archive/Anaconda-1.6.0-Linux-x86_64.sh
  - chmod +x Anaconda-1.6.0-Linux-x86_64.sh
  - ./Anaconda-1.6.0-Linux-x86_64.sh -b
  - PYTHONPATH= PATH=/home/travis/anaconda/bin:$PATH pip install -r requirements.txt --use-mirrors
  - PYTHONPATH= PATH=/home/travis/anaconda/bin:$PATH pip install patsy --use-mirrors
  - PYTHONPATH= PATH=/home/travis/anaconda/bin:$PATH pip install msgpack_python --use-mirrors
  - cp src/settings.py.example src/settings.py
  - pip install pep8 --use-mirrors
script:
  - PYTHONPATH= PATH=/home/travis/anaconda/bin:$PATH nosetests -v --nocapture
  - pep8 --exclude=migrations --ignore=E501,E251 ./ 
notifications:
  email: false
